### ISSUE TITLE
Serve api specification from web address, not from file

### ISSUE THREAD

**Issue by cinderell4** [PWZER/swagger-ui-py#2]
Especially for developing purposes and not following the spec first approach it would be nice if it wouldn't be necessary to write a file to disc before using swagger-ui-py. Serving from a web address is appreciated.
Thanks for your work so far.

**Comment by richardhector** [comment]
Yes, this would be great!

**Comment by PWZER** [comment]
@cinderell4 @richardhector  You can see [v0.1.6](https://github.com/PWZER/swagger-ui-py/releases/tag/v0.1.6) is accord with your demand.
