### ISSUE TITLE
Update swagger-ui to 5.0.0

### ISSUE THREAD

**Issue by kshpytsya** [PWZER/swagger-ui-py#38]
Swagger-ui 5.0.0 has been released two months ago and adds support for OpenAPI spec 3.1.0 which adds a lot of improvements to complex types.

**Comment by PWZER** [comment]
@kshpytsya  You can see the [latest version](https://github.com/PWZER/swagger-ui-py/releases/tag/v23.08.23)

**Comment by kshpytsya** [comment]
Great! Works for me and has saved me a couple of dozens of lines of code that was doing conversion of OAS3.1 to OAS3.0 just to make it usable with swagger-ui.
