### ISSUE TITLE
examples not working on requestBody

### ISSUE THREAD

**Issue by tamarmot** [PWZER/swagger-ui-py#5]
Per the api specification, requestBody should support example OR examples:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#requestBodyObject

If I include example, it works and shows up in the ui.

If I include examples, it does NOT show up in the ui.
However, I can verify the examples work in this swagger editor:

https://editor.swagger.io/

**Comment by tamarmot** [comment]
If I check out your source code and update the ui and the editor, it works.  Time for an updated release?  I had pulled the library from pip initially.

**Comment by PWZER** [comment]
@tamarmot Thank you for all your contributions. a release version has been updated.
